# Copyright (c) Microsoft. All rights reserved.

"""
Export Handler - Export conversations and responses to various formats.
Phase 4: Engagement Features
"""

import json
import logging
from typing import Dict, Any, List, Optional
from datetime import datetime
from io import BytesIO

logger = logging.getLogger(__name__)


class ExportHandler:
    """
    Handles exporting conversations, responses, and documents to various formats.
    Supports JSON, TXT, and Markdown formats.
    """
    
    def __init__(self):
        """Initialize the export handler."""
        logger.info("ExportHandler initialized")
    
    def export_response_to_json(self, response_data: Dict[str, Any]) -> str:
        """
        Export a single response to JSON format.
        
        Args:
            response_data: Response data with query, answer, metadata
            
        Returns:
            JSON string
        """
        export_data = {
            "type": "legal_response",
            "exported_at": datetime.utcnow().isoformat(),
            "query": response_data.get("query", ""),
            "response": response_data.get("response", ""),
            "confidence": response_data.get("confidence", 0.0),
            "source": response_data.get("source", ""),
            "language": response_data.get("language", "English"),
            "metadata": response_data.get("metadata", {})
        }
        
        return json.dumps(export_data, indent=2, ensure_ascii=False)
    
    def export_response_to_txt(self, response_data: Dict[str, Any]) -> str:
        """
        Export a single response to plain text format.
        
        Args:
            response_data: Response data
            
        Returns:
            Plain text string
        """
        lines = [
            "=" * 80,
            "AI LEGAL ENGINE - RESPONSE EXPORT",
            "=" * 80,
            "",
            f"Exported: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
            "",
            "QUERY:",
            "-" * 80,
            response_data.get("query", ""),
            "",
            "RESPONSE:",
            "-" * 80,
            response_data.get("response", ""),
            "",
            "METADATA:",
            "-" * 80,
            f"Confidence: {response_data.get('confidence', 0.0)}",
            f"Source: {response_data.get('source', '')}",
            f"Language: {response_data.get('language', 'English')}",
            "",
            "=" * 80,
        ]
        
        return "\n".join(lines)
    
    def export_response_to_markdown(self, response_data: Dict[str, Any]) -> str:
        """
        Export a single response to Markdown format.
        
        Args:
            response_data: Response data
            
        Returns:
            Markdown string
        """
        lines = [
            "# AI Legal Engine - Response Export",
            "",
            f"**Exported:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
            "",
            "## Query",
            "",
            response_data.get("query", ""),
            "",
            "## Response",
            "",
            response_data.get("response", ""),
            "",
            "## Metadata",
            "",
            f"- **Confidence:** {response_data.get('confidence', 0.0)}",
            f"- **Source:** {response_data.get('source', '')}",
            f"- **Language:** {response_data.get('language', 'English')}",
            "",
            "---",
            "",
            "*Generated by AI Legal Engine*",
        ]
        
        return "\n".join(lines)
    
    def export_conversation_to_json(
        self,
        conversation_data: Dict[str, Any],
        messages: List[Dict[str, Any]]
    ) -> str:
        """
        Export a full conversation to JSON format.
        
        Args:
            conversation_data: Conversation metadata
            messages: List of messages in conversation
            
        Returns:
            JSON string
        """
        export_data = {
            "type": "conversation_export",
            "exported_at": datetime.utcnow().isoformat(),
            "conversation": {
                "id": conversation_data.get("id"),
                "title": conversation_data.get("title", "Untitled Conversation"),
                "created_at": conversation_data.get("created_at"),
                "message_count": len(messages),
                "status": conversation_data.get("status", "active")
            },
            "messages": [
                {
                    "role": role,
                    "content": msg.get("content", ""),
                    "timestamp": msg.get("created_at"),
                    "language": msg.get("language", "English"),
                    "confidence": msg.get("confidence"),
                    "metadata": msg.get("metadata", {})
                }
                for msg in messages
                for role in [msg.get("role", "user")]
            ]
        }
        
        return json.dumps(export_data, indent=2, ensure_ascii=False)
    
    def export_conversation_to_txt(
        self,
        conversation_data: Dict[str, Any],
        messages: List[Dict[str, Any]]
    ) -> str:
        """
        Export a full conversation to plain text format.
        
        Args:
            conversation_data: Conversation metadata
            messages: List of messages
            
        Returns:
            Plain text string
        """
        lines = [
            "=" * 80,
            "AI LEGAL ENGINE - CONVERSATION EXPORT",
            "=" * 80,
            "",
            f"Title: {conversation_data.get('title', 'Untitled Conversation')}",
            f"Created: {conversation_data.get('created_at', 'Unknown')}",
            f"Messages: {len(messages)}",
            f"Exported: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
            "",
            "=" * 80,
            ""
        ]
        
        for i, msg in enumerate(messages, 1):
            role = msg.get("role", "user").upper()
            content = msg.get("content", "")
            timestamp = msg.get("created_at", "")
            
            lines.extend([
                f"[{i}] {role} - {timestamp}",
                "-" * 80,
                content,
                "",
            ])
        
        lines.extend([
            "=" * 80,
            "End of Conversation",
            "=" * 80,
        ])
        
        return "\n".join(lines)
    
    def export_conversation_to_markdown(
        self,
        conversation_data: Dict[str, Any],
        messages: List[Dict[str, Any]]
    ) -> str:
        """
        Export a full conversation to Markdown format.
        
        Args:
            conversation_data: Conversation metadata
            messages: List of messages
            
        Returns:
            Markdown string
        """
        lines = [
            "# AI Legal Engine - Conversation Export",
            "",
            f"**Title:** {conversation_data.get('title', 'Untitled Conversation')}",
            f"**Created:** {conversation_data.get('created_at', 'Unknown')}",
            f"**Messages:** {len(messages)}",
            f"**Exported:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
            "",
            "---",
            ""
        ]
        
        for i, msg in enumerate(messages, 1):
            role = msg.get("role", "user")
            content = msg.get("content", "")
            timestamp = msg.get("created_at", "")
            
            role_emoji = "👤" if role == "user" else "🤖"
            role_title = "User" if role == "user" else "Assistant"
            
            lines.extend([
                f"## {role_emoji} {role_title} - Message {i}",
                "",
                f"*{timestamp}*",
                "",
                content,
                "",
                "---",
                ""
            ])
        
        lines.append("*Generated by AI Legal Engine*")
        
        return "\n".join(lines)
    
    def export_document(
        self,
        document_data: Dict[str, Any],
        format: str = "txt"
    ) -> str:
        """
        Export a generated document.
        
        Args:
            document_data: Document data with content and metadata
            format: Export format (txt, md)
            
        Returns:
            Formatted string
        """
        if format == "md":
            return self._export_document_markdown(document_data)
        else:
            return self._export_document_txt(document_data)
    
    def _export_document_txt(self, document_data: Dict[str, Any]) -> str:
        """Export document to plain text."""
        lines = [
            "=" * 80,
            f"{document_data.get('template_type', 'DOCUMENT').upper()}",
            "=" * 80,
            "",
            f"Title: {document_data.get('title', 'Untitled')}",
            f"Created: {document_data.get('created_at', 'Unknown')}",
            f"Status: {document_data.get('status', 'draft')}",
            "",
            "=" * 80,
            "",
            document_data.get('content', ''),
            "",
            "=" * 80,
        ]
        
        return "\n".join(lines)
    
    def _export_document_markdown(self, document_data: Dict[str, Any]) -> str:
        """Export document to Markdown."""
        lines = [
            f"# {document_data.get('title', 'Untitled Document')}",
            "",
            f"**Type:** {document_data.get('template_type', 'document')}",
            f"**Created:** {document_data.get('created_at', 'Unknown')}",
            f"**Status:** {document_data.get('status', 'draft')}",
            "",
            "---",
            "",
            document_data.get('content', ''),
            "",
            "---",
            "",
            "*Generated by AI Legal Engine Document Generator*",
        ]
        
        return "\n".join(lines)


# Global instance
_export_handler = None


def get_export_handler() -> ExportHandler:
    """Get or create the global export handler instance."""
    global _export_handler
    if _export_handler is None:
        _export_handler = ExportHandler()
    return _export_handler
